name: 'Create an Open Catalogi page'
author: 'Open Catalogi'
description: 'Creates an Open Catalogi page for a specific organisation'

branding:
  icon: 'file-plus'
  color: 'blue'

inputs:
  # General
  favicon_logo:
    description: 'A base64 encoded SVG file or URL to the logo used as favicon'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  page_title:
    description: 'The title for the website / gitpage'
    required: false
    type: string
    default: ${{ github.event.repository.name }}
  nl_design_theme_classname:
    description: 'The class name of the desired NL design theme'
    required: false
    type: string
    default: 'open-webconcept-theme'
  start_page:
    description: 'When given, shows a readme file instead of the normal start page'
    required: false
    type: string
    default: 'false'

  # Filters
  filter_forks:
    description: 'If you want to have the filter forks displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_rating:
    description: 'What kind of rating must be shown, OpenCatalogi or Commonground'
    required: false
    type: string
    default: 'OpenCatalogi'
  filter_layer:
    description: 'If you want to have the filter layer displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_upl:
    description: 'If you want to have the filter upl displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_organisation:
    description: 'If you want to have the filter organisation displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_category:
    description: 'If you want to have the filter category displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_platforms:
    description: 'If you want to have the filter platforms displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_status:
    description: 'If you want to have the filter status displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_maintenance_types:
    description: 'If you want to have the filter maintenance types displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_license:
    description: 'If you want to have the filter license displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_business_fuctions:
    description: 'If you want to have the filter business functions displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_software_types:
    description: 'If you want to have the filter software types displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_business_services:
    description: 'If you want to have the filter business services displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '
  filter_reference_components:
    description: 'If you want to have the filter reference components displayed, set to false to not show the filter'
    required: false
    type: string
    default: ' '

  # Header
  navbar_show_login:
    description: 'Shows the login option'
    required: false
    type: boolean
    default: false
  navbar_logo:
    description: 'A base64 encoded SVG file or URL to the logo used in the main menu'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  navbar_content:
    description: 'A link to the JSON file that manages the footer content'
    required: false
    type: string
    default: 'https://raw.githubusercontent.com/OpenCatalogi/web-app/348679b7537b20e51767dfdc6086349602afe219/pwa/src/templates/templateParts/header/HeaderContent.json'

  # Jumbotron
  jumbotron_title:
    description: 'The title of the jumbotron'
    required: false
    type: string
    default: ${{ github.event.repository.name }}
  jumbotron_subtitle:
    description: 'The (short) subtitle used in the jumbotron'
    required: false
    type: string
    default: 'Product page'
  jumbotron_description:
    description: 'The (long) description included in the jumbotron)'
    required: false
    type: string
    default: ${{ github.event.repository.description }}

  jumbotron_searchform:
    description: 'Whether or not to display the search form'
    required: false
    type: boolean
    default: false
  jumbotron_iscard:
    description: 'Put the content o the jumbotron within a card'
    required: false
    type: boolean
    default: false
  jumbotron_image_placement:
    description: 'The position of the jumbotron image ("false" | "background" | "right" | "left")'
    required: false
    type: string
    default: "false"
  jumbotron_image_url:
    description: 'A base64 encoded SVG file or URL to the logo used in the jumbotron'
    required: false
    type: string
    default: "false"

  # Footer
  footer_logo:
    description: 'A base64 encoded SVG file or URL to the logo used in the footer'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  footer_content:
    description: 'An link to the json file that manages the footer content'
    required: false
    type: string
    default: 'https://raw.githubusercontent.com/OpenCatalogi/web-app/25995205e1dbb043822d1c58c5c23f8e6f77ff7e/pwa/src/templates/templateParts/footer/FooterContent.json'
  footer_show_creator:
    description: 'Shows the "<> with love from Conduction" link'
    required: false
    type: boolean
    default: true

  # Open Catalogi / Old settings (depracticed)
  me_url:
    description: 'The me (profile) url used'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/api/users/me'
  api_url:
    description: 'The location of the open catalogi api (change if you are running your own api)'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/api'
  admin_url:
    description: 'The admin (dashboard) url used'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/admin'
  base_url:
    description: 'The BASE location of the open catalogi api (change if you are running your own api)'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl'
  frontend_url:
    description: 'the location (url) of this open catalogi installation'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl'
  login_redirect:
    description: 'publiccode.yml path'
    required: false
    type: string
    default: 'vault'
  admin_dashboard_url:
    description: 'the location of the pen catalogi dashboard'
    required: false
    type: string
    default: 'https://admin.opencatalogi.nl'
  arrow_breadcrumbs:
    description: 'Whether to use arrow breadcrumbs instead of the normal breadcrumbs'
    required: false
    type: boolean
    default: false

  # Build configuration
  env_vars_set:
    description: 'Whether to use the env variables set in this file, set to false to use env variables of the OpenCatalogi config files'
    required: true
    type: boolean
    default: true
  github_pages_branch:
    description: 'The branch on which the GitHub page will be build'
    required: false
    type: string
    default: 'gh-pages'
  github_repository_name_as_prefix:
    description: 'Whether to use the GitHub repository name as a prefix, set to false when using a custom domain'
    required: false
    type: boolean
    default: true
  repository:
    description: 'The GitHub repository to use (could be an external repository)'
    required: false
    type: string
    default: ${{ github.event.repository.name }}
  pull_from_branche:
    description: 'The branch on which to base the build, e.g. main or development'
    required: false
    type: string
    default: 'main'

  # Git Configuration
  git_name:
    description: 'Git name configuration for the commit'
    required: false
    type: string
    default: 'Open Catalogi bot'
  git_mail:
    description: 'Git mail configuration for the commit'
    required: false
    type: string
    default: 'bot@opencatalogi.nl'
  git_commit_message:
    description: 'The description for the commit'
    required: false
    type: string
    default: ${{ github.event.repository.html_url }}
  github_organization_url:
    description: 'The repository to which the results are limited (used to only look in your own organization)'
    required: false
    type: string
    default: 'https://github.com/${{ github.repository_owner }}'


outputs:
  page:
    description: 'A zip of the build page'

runs:
  using: "composite"
  steps:
    # Lets check al the environment variables that we are using
    - name: Print env variables
      shell: bash
      run: env | sort
    - name: Get the Open Catalogi Web APP
      uses: actions/checkout@v2
      with:
        repository: OpenCatalogi/web-app
        ref: ${{ inputs.pull_from_branche }}

    # With special thanxs to https://github.com/SpicyPizza/create-envfile
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_GATSBY_ENV_VARS_SET: ${{ inputs.env_vars_set }}
        envkey_GATSBY_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ inputs.github_repository_name_as_prefix }}
        envkey_GATSBY_GITHUB_REPOSITORY_NAME: ${{ inputs.repository }}
        envkey_GATSBY_OPTIONAL_START_PAGE: ${{ inputs.start_page }}
        envkey_GATSBY_FILTER_FORKS: ${{ inputs.filter_forks }}
        envkey_GATSBY_FILTER_RATING: ${{ inputs.filter_rating }}
        envkey_GATSBY_FILTER_LAYER: ${{ inputs.filter_layer }}
        envkey_GATSBY_FILTER_UPL: ${{ inputs.filter_upl }}
        envkey_GATSBY_FILTER_ORGANISATION: ${{ inputs.filter_organisation }}
        envkey_GATSBY_FILTER_CATEGORY: ${{ inputs.filter_category }}
        envkey_GATSBY_FILTER_PLATFROMS: ${{ inputs.filter_platforms }}
        envkey_GATSBY_FILTER_STATUS: ${{ inputs.filter_status }}
        envkey_GATSBY_FILTER_MAINTENANCE_TYPES: ${{ inputs.filter_maintenance_types }}
        envkey_GATSBY_FILTER_LICENSE: ${{ inputs.filter_license }}
        envkey_GATSBY_FILTER_BUSINESS_FUNCTIONS: ${{ inputs.filter_business_functions }}
        envkey_GATSBY_FILTER_SOFTWARE_TYPES: ${{ inputs.filter_software_types }}
        envkey_GATSBY_FILTER_BUSINESS_SERVICES: ${{ inputs.filter_business_services }}
        envkey_GATSBY_FILTER_REFERENCE_COMPONENTS: ${{ inputs.filter_reference_components }}
        envkey_GATSBY_ME_URL: ${{ inputs.me_url }}
        envkey_GATSBY_API_URL: ${{ inputs.api_url }}
        envkey_GATSBY_ADMIN_URL: ${{ inputs.admin_url }}
        envkey_GATSBY_BASE_URL: ${{ inputs.base_url }}
        envkey_GATSBY_FRONTEND_URL: ${{ inputs.frontend_url }}
        envkey_GATSBY_LOGIN_REDIRECT: ${{ inputs.login_redirect }}
        envkey_GATSBY_ADMIN_DASHBOARD_URL: ${{ inputs.admin_dashboard_url }}
        envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ inputs.nl_design_theme_classname }}
        envkey_GATSBY_ARROW_BREADCRUMBS: ${{ inputs.arrow_breadcrumbs }}
        envkey_GATSBY_FAVICON_URL: ${{ inputs.favicon_logo }}
        envkey_GATSBY_HEADER_LOGO_URL: ${{ inputs.navbar_logo }}
        envkey_GATSBY_HEADER_SHOW_LOGIN: ${{ inputs.navbar_show_login }}
        envkey_GATSBY_HEADER_CONTENT: ${{ inputs.navbar_content }}
        envkey_GATSBY_FOOTER_LOGO_URL: ${{ inputs.footer_logo }}
        envkey_GATSBY_FOOTER_SHOW_CREATOR: ${{ inputs.footer_show_creator }}
        envkey_GATSBY_FOOTER_CONTENT: ${{ inputs.footer_content }}
        envkey_GATSBY_GITHUB_ORGANIZATION_URL: ${{ inputs.github_organization_url }}
        envkey_GATSBY_JUMBOTRON_TITLE: ${{ inputs.jumbotron_title }}
        envkey_GATSBY_JUMBOTRON_SUBTITLE: ${{ inputs.jumbotron_subtitle }}
        envkey_GATSBY_JUMBOTRON_DESCRIPTION: ${{ inputs.jumbotron_description }}
        envkey_GATSBY_JUMBOTRON_SEARCHFORM: ${{ inputs.jumbotron_searchform }}
        envkey_GATSBY_JUMBOTRON_ISCARD: ${{ inputs.jumbotron_iscard }}
        envkey_GATSBY_JUMBOTRON_IMAGE_PLACEMENT: ${{ inputs.jumbotron_image_placement }}
        envkey_GATSBY_JUMBOTRON_IMAGE_URL: ${{ inputs.jumbotron_image_url }}

        directory: pwa/static
        file_name: .env.production
        fail_on_empty: true
        sort_keys: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      shell: bash
      run: cd pwa && npm install

    - name: Install parcel/watcher
      shell: bash
      run: cd pwa && npm install @parcel/watcher

    - name: Remove old Gatsby cache
      shell: bash
      run: rm -rf pwa/.cache

    - name: Build application
      shell: bash
      run: cd pwa && npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.github_pages_branch }}
        folder: pwa/public
        git-config-name: ${{ inputs.git_name }}
        git-config-email: ${{ inputs.git_mail }}
        commit-message: ${{ inputs.git_commit_message }}

