name: 'Create an Open Catalogi page'
author: 'Open Catalogi'
description: 'Creates an Open Catalogi page for a specific organisation'

branding:
  icon: 'file-plus'
  color: 'blue'

inputs:
  # Build configuration
  github_pages_branch:
    description: 'The banche on wish the github page wil be build'
    required: false
    type: string
    default: 'gh-pages'
  github_repository_name_as_prefix:
    description: 'Whether to use the github repository name as a prefix, set to false when using a custom domain'
    required: false
    type: boolean
    default: true
  repository:
    description: 'The github repository to use (could be an external repository)'
    required: false
    type: string
    default: ${{ github.event.repository.name }}
  pull_from_branche:
    description: 'The branche on witch to base the build e.g. main or development'
    required: false
    type: string
    default: 'main'

  # Old settings (depracticed)
  me_url:
    description: 'The me (profile) url used'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/api/users/me'
  api_url:
    description: 'The location of the open catalogi api (change if you are running your own api)'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/api'
  admin_url:
    description: 'The admin (dashboard) url used'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl/admin'
  base_url:
    description: 'The BASE location of the open catalogi api (change if you are running your own api)'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl'
  frontend_url:
    description: 'the location (url) of this open catalogi installation'
    required: false
    type: string
    default: 'https://api.opencatalogi.nl'
  login_redirect:
    description: 'publiccode.yml path'
    required: false
    type: string
    default: 'vault'
  admin_dashboard_url:
    description: 'the location of the pen catalogi dashboard'
    required: false
    type: string
    default: 'https://admin.opencatalogi.nl'

  # General
  favicon_logo:
    description: 'An base64 encoded svg file or url to the logo used as favicon'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  nl_design_theme_classname:
    description: 'the class name of the desired nl design theme'
    required: false
    type: string
    default: 'open-webconcept-theme'
  arrow_breadcrumbs:
    description: 'whether to use arrow breadcrums instead of the normal breadcrumbs'
    required: false
    type: boolean
    default: false
  start_page:
    description: 'When given shows a readme file instead of the normal start page'
    required: false
    type: string
    default: 'https://github.com/OpenCatalogi/web-app/blob/development/README.md'
  # Header
  navbar_logo:
    description: 'An base64 encoded svg file or url to the logo used in the main menu'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  navbar_show_login:
    description: 'Shows the inloggen option'
    required: false
    type: boolean
    default: fasle
  navbar_content:
    description: 'An link to the json file that manages the footer content'
    required: false
    type: string
    default: 'https://raw.githubusercontent.com/OpenCatalogi/web-app/348679b7537b20e51767dfdc6086349602afe219/pwa/src/templates/templateParts/header/HeaderContent.json'
  # Jumbotran

  # Footer
  footer_logo:
    description: 'An base64 encoded svg file or url to the logo used in the footer'
    required: false
    type: string
    default: 'https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo@2x.png'
  footer_content:
    description: 'An link to the json file that manages the footer content'
    required: false
    type: string
    default: 'https://raw.githubusercontent.com/OpenCatalogi/web-app/25995205e1dbb043822d1c58c5c23f8e6f77ff7e/pwa/src/templates/templateParts/footer/FooterContent.json'
  footer_show_creator:
    description: 'Shows the <> with love from conduction link'
    required: false
    type: boolean
    default: true


  # git configuration
  git_name:
    description: 'Git name configuration for the commit'
    required: false
    type: string
    default: 'Open Catalogi bot'
  git_mail:
    description: 'Git mail configuration for the commit'
    required: false
    type: string
    default: 'bot@opencatalogi.nl'
  git_commit_message:
    description: 'The description for the  commit'
    required: false
    type: string
    default: ${{ github.event.repository.html_url }}


outputs:
  page:
    description: 'A zip of the build page'

runs:
  using: "composite"
  steps:
    - name: Get the Open Catalogi Web APP
      uses: actions/checkout@v2
      with:
        repository: OpenCatalogi/web-app
        ref: ${{ inputs.pull_from_branche }}

    # With special thanxs to https://github.com/SpicyPizza/create-envfile
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_GATSBY_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ inputs.github_repository_name_as_prefix }}
        envkey_GATSBY_GITHUB_REPOSITORY_NAME: ${{ inputs.repository }}
        envkey_GATSBY_OPTIONAL_START_PAGE: ${{ inputs.start_page }}
        envkey_GATSBY_ME_URL: ${{ inputs.me_url }}
        envkey_GATSBY_API_URL: ${{ inputs.api_url }}
        envkey_GATSBY_ADMIN_URL: ${{ inputs.admin_url }}
        envkey_GATSBY_BASE_URL: ${{ inputs.base_url }}
        envkey_GATSBY_FRONTEND_URL: ${{ inputs.frontend_url }}
        envkey_GATSBY_LOGIN_REDIRECT: ${{ inputs.login_redirect }}
        envkey_GATSBY_ADMIN_DASHBOARD_URL: ${{ inputs.admin_dashboard_url }}
        envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ inputs.nl_design_theme_classname }}
        envkey_GATSBY_ARROW_BREADCRUMBS: ${{ inputs.arrow_breadcrumbs }}
        envkey_GATSBY_FAVICON_URL: ${{ inputs.favicon_logo }}
        envkey_GATSBY_HEADER_LOGO_URL: ${{ inputs.navbar_logo }}
        envkey_GATSBY_HEADER_SHOW_LOGIN: ${{ inputs.navbar_show_login }}
        envkey_GATSBY_HEADER_CONTENT: ${{ inputs.navbar_content }}
        envkey_GATSBY_FOOTER_LOGO_URL: ${{ inputs.footer_logo }}
        envkey_GATSBY_FOOTER_SHOW_CREATOR: ${{ inputs.footer_show_creator }}
        envkey_GATSBY_FOOTER_CONTENT: ${{ inputs.footer_content }}
        # envkey_GATSBY_GITHUB_ORGANIZATION_URL: ${{ env.GITHUB_ORGANIZATION_URL }}

        directory: pwa/static
        file_name: .env.production
        fail_on_empty: true
        sort_keys: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      shell: bash
      run: cd pwa && npm install

    - name: Remove old Gatsby cache
      shell: bash
      run: rm -rf pwa/.cache

    - name: Build application
      shell: bash
      run: cd pwa && npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.github_pages_branch }}
        folder: pwa/public
        git-config-name: ${{ inputs.git-name }}
        git-config-email: ${{ inputs.git-mail }}
        commit-message: ${{ inputs.git-commit-message }}

