name: My Open Catalogi Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - action-test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/opencatalogi-action@130a40cccbd3d727d76c54d7b46ddee79b483c83